name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: # a led
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}   # Use matrix node-version
        cache: 'npm'                               # Cache npm dependencies
    - run: npm install                           # Use npm install to install dependencies
    - run: npm run migrate-deploy                # Run migration/deploy script
    - run: npm test                              # Run tests
